name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Format
      uses: actions-rust-lang/rustfmt@v1
    - run: cargo install clippy
    - name: Run Clippy
      run: |
        cd src
        clippy --all --workspace
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
