name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: clippy
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Format
      uses: actions-rust-lang/rustfmt@v1
    - name: Clippy
      uses: actions-rs/clippy@master
      with:
        args: --all-features --all-targets
    - run: sudo apt-get install pkg-config libgtk-3-dev libsoup2.4-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
