name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install frontend dependecies
      run: npm install
    - name: Tauri
      run: cargo tauri dev
